### PR TITLE
small CSS optimizations + minor content shuffling

### PR DESCRIPTION
**Pull request by malsf21**
Hey Derptemeus,

I’m a big fan of your site (I used to use it all the time when playing normals so I knew which champs to play), and in the spirit of hacktoberfest I made a few small changes that should make the site slightly better:

* Small CSS files -> style tags - since the process of fetching each file is render blocking and they’re only called once, so a style tag can alleviate some of those problems
* Bootstrap Grid - I noticed that there were some awkward uses of the grid, so I used .container and .row to make the content more responsive on mobile screen sizes. Functionality is almost the same
* Navbar widening - I changed .container to .container-fluid and made the "lookup" button change to a search icon at the `md` screen size, so the awkward 2-row navbar happens at less breakpoints
* Highscores restructure - I removed all the .pull-left and used Bootstrap’s Grid system instead, which again makes it look better on mobile. No more overlap! Generally it still looks the same though
* Minor content fixes: I added some punctuation and spacing to the FAQ

If there’s something wrong let me know - once again, great job on the website and keep up your good work!

### CODE REVIEW

**Comment by Derpthemeus** [comment]
Sorry I haven't had a chance to look over this yet. I've been pretty busy recently, but I should have time to check it out soon™.

**Comment by Derpthemeus** [comment]
Thanks for the PR! Overall these look good, but there are 2 minor issues.
___
>Small CSS files -> style tags - since the process of fetching each file is render blocking and they’re only called once, so a style tag can alleviate some of those problems

I ran a few quick tests, and didn't see any performance gains when from using internal CSS tags. I'm no expert on the subject, but I think that these changes didn't have any effect because CSS downloads are bottlenecked by Bootstrap; CSS downloads occur in parallel, so only the slowest download affects performance. Since there don't seem to be any performance gains and I personally find the separate files to be neater, I'd like to revert this change.

>Highscores restructure - I removed all the .pull-left and used Bootstrap’s Grid system instead, which again makes it look better on mobile. No more overlap! Generally it still looks the same though

Looks much better on most mobile devices, but there are some overlap issues at certain screen sizes ([when the window is  slightly too large to use 1 column instead of 2](https://i.gyazo.com/7f3faca045261bf16f969cfc03d26689.png), and [at sizes below ~340px](https://i.gyazo.com/85105d5038be5b0ccaf9122e5cc6158a.png)). Overall these changes definitely are an improvement and acceptable as-is, but it would be awesome if you could also fix this minor issue (I tried to fix it myself, but I suck with CSS and couldn't figure out a solution).
___

If you don't mind accepting the changes I requested, I'll squash the commits and merge the PR.

**Comment by malsf21** [comment]
Awesome, thanks for pointing those two things out - I accepted your PR, and I'll see if I can think of something to fix the overlap with the highscores. I'll probably comment again if I think of something (or not).

**Comment by malsf21** [comment]
As a side-note, I know for sure we can recompile Bootstrap using different pixel cutoffs for each breakpoint (xs, sm, md, lg), but that could also break other parts of the site. I'll see if I can hard-code in a media query that can adapt the champion portrait right-margin or change the grid size again.

**Comment by Derpthemeus** [comment]
Thanks for your contribution!

**Pull request merged**
